<a href="https://colab.research.google.com/github/akbarovyodgorbek931-hue/Yodgor1/blob/main/pandas_3_ipynd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
upload = files.upload()

Saving pandas_homework_dirty_data_2150_rows.csv to pandas_homework_dirty_data_2150_rows.csv

In [ ]:
df=pd.read_csv("pandas_homework_dirty_data_2150_rows.csv")
df.head()

   order_id    shop  product     city amount   shop_date
0         1  Shop B   Laptop  Bukhara   3950  16.01.2025
1         2  Shop E   Laptop      NaN   1393         NaN
2         3     NaN  Monitor      NaN  1,200  17.09.2025
3         4     NaN      NaN  Bukhara   2456  21.01.2025
4         5     NaN   Laptop      NaN   4715  14.01.2025

In [ ]:
df["shop"] = df["shop"].fillna("magazin")

In [36]:
df.head()

,order_id,shop,product,city,amount,shop_date,priduct
0,1,Shop B,Laptop,Bukhara,3950,16.01.2025,Laptop
1,2,Shop E,Laptop,bukhara_nan,1393,16.01.2025_nan,Laptop
2,3,magazin,Monitor,bukhara_nan,"1,200",17.09.2025,Monitor
3,4,magazin,monitor_Bukhara,Bukhara,2456,21.01.2025,monitor_Bukhara
4,5,magazin,Laptop,bukhara_nan,4715,14.01.2025,Laptop

In [35]:
df["shop_date"] = df["shop_date"].fillna(method="ffill")